package compiler

import (
	"fmt"
	"strings"

	"github.com/fahmitech/wpc/pkg/types"
)

// RenderPowerShell generates a Windows PowerShell script for the policy
func RenderPowerShell(policy *types.Policy) (string, error) {
	var sb strings.Builder

	sb.WriteString("# Generated by WPC (WirePolicy Compiler)\n")
	sb.WriteString("$ErrorActionPreference = 'Stop'\n\n")

	// 1. Transactional Setup (Spec 5.1)
	sb.WriteString("$ID = \"WPC-\" + (Get-Date -Format \"HHmmss\")\n")
	sb.WriteString(fmt.Sprintf("Write-Host \"[INFO] Applying policy version %s with Session ID $ID\"\n\n", policy.Version))

	// 2. Spec #10: Profile Enforcement
	sb.WriteString(fmt.Sprintf("Set-NetConnectionProfile -InterfaceAlias \"%s\" -NetworkCategory Private\n\n", policy.Global.Interface))

	// 3. Render Rules
	for _, rule := range policy.Rules {
		// Direction Inbound (Spec 5.2)
		sb.WriteString(renderPSRule(rule, "Inbound", "$ID"))
		
		// Spec #9: Forwarding Scope (Duplicate for Forward)
		sb.WriteString(renderPSRule(rule, "Forward", "$ID"))
	}

	// 4. Cleanup old rules (Spec 5.1)
	sb.WriteString("\n# Cleanup old WPC rules\n")
	sb.WriteString("Get-NetFirewallRule -Group \"WPC-*\" | Where-Object { $_.Group -ne $ID } | Remove-NetFirewallRule\n")
	sb.WriteString("Write-Host \"[INFO] Policy applied successfully.\"\n")

	return sb.String(), nil
}

func renderPSRule(rule types.Rule, direction string, groupID string) string {
	var sb strings.Builder
	
	action := "Allow"
	if strings.EqualFold(rule.Action, "drop") {
		action = "Block"
	}

	// Build sources and destinations
	srcs := []string{}
	for _, p := range rule.SrcPrefixes {
		srcs = append(srcs, p.String())
	}
	
	dsts := []string{}
	for _, p := range rule.DstPrefixes {
		dsts = append(dsts, p.String())
	}

	// Windows Firewall uses "Any" if list is empty, but we want to be explicit if possible
	srcStr := "Any"
	if len(srcs) > 0 {
		srcStr = strings.Join(srcs, ",")
	}
	
	dstStr := "Any"
	if len(dsts) > 0 {
		dstStr = strings.Join(dsts, ",")
	}

	protocol := rule.Protocol
	if strings.EqualFold(protocol, "any") {
		protocol = "Any"
	}

	port := rule.Port
	if strings.EqualFold(port, "any") {
		port = "Any"
	}

	displayName := rule.Name
	if displayName == "" {
		displayName = fmt.Sprintf("WPC-%s-%s", direction, rule.Protocol)
	}

	sb.WriteString(fmt.Sprintf("New-NetFirewallRule -DisplayName \"%s\" -Direction %s -Action %s -Protocol %s ", 
		displayName, direction, action, protocol))
	
	if port != "Any" {
		sb.WriteString(fmt.Sprintf("-LocalPort %s ", port))
	}
	
	if srcStr != "Any" {
		sb.WriteString(fmt.Sprintf("-RemoteAddress %s ", srcStr))
	}
	
	if dstStr != "Any" {
		sb.WriteString(fmt.Sprintf("-LocalAddress %s ", dstStr))
	}

	sb.WriteString(fmt.Sprintf("-Group %s\n", groupID))

	return sb.String()
}
